Server:
  addr: "0.0.0.0"
  port: ":8080"

Rabbit:
  addr: "amqp://guest:guest@rabbitmq:5672/"

Postgres:
  addr: "postgres://postgres:StrongPassw@postgres:5432/db"
  user: "postgres"
  password: "StrongPassw"
  db_name: "db"

Redis:
  addr: "redis:6379"
  user:
  password:
  db: 0
  maxRetries: 5
  dialTimeout: 10
  timeout: 5

Logger:
  level: "debug"

