# Адрес сервера, на котором запускается сервис
Server:
  addr: "0.0.0.0"
  port: ":8080"

# Параметры RabbitMQ
Rabbit:
  addr: "amqp://guest:guest@rabbitmq:5672/"

# Параметры Redis
Redis:
  addr: "redis:6379"
  user:
  password:
  db: 0
  maxRetries: 5
  dialTimeout: 10
  timeout: 5

# Параметры логирования
Logger:
  level: "debug"  # debug, info, warn, error

